//------------------------------------------------------------------
// Proxy Unit Generated by Delphi Microservices Container 4.1.60
// Do not modify this unit!
// Generated at: 2022-12-13 10:27:41
//------------------------------------------------------------------
unit CalculatorRPCProxy;

interface

uses
  System.SysUtils,
  System.Classes,
  MVCFramework.JSONRPC,
  MVCFramework.JSONRPC.Client,
  MVCFramework.Serializer.Commons,
  System.Net.URLClient,
  JsonDataObjects;

type
  ICalculatorRPCProxy = interface
  ['{9E0BE466-1762-4F51-91D0-30407933D3E7}']
    function RPCExecutor: IMVCJSONRPCExecutor;
    procedure IgnoreInvalidCert;
    /// <summary>
    /// Invokes [function Sum(const A: Integer; const B: Integer): Integer]
    /// Returns the sum of two integers
    /// </summary>
    function Sum(const A: Integer; const B: Integer): Integer;
    /// <summary>
    /// Invokes [function Diff(const A: Integer; const B: Integer): Integer]
    /// Returns the difference between two integers
    /// </summary>
    function Diff(const A: Integer; const B: Integer): Integer;
  end;

  TCalculatorRPCProxy = class(TInterfacedObject, ICalculatorRPCProxy)
  protected
    fRPCExecutor: IMVCJSONRPCExecutor;
    function NewReqID: Int64;
    procedure IgnoreInvalidServerCertificate(const Sender: TObject;
      const ARequest: TURLRequest; const Certificate: TCertificate; var Accepted: Boolean);
  public
    function RPCExecutor: IMVCJSONRPCExecutor;
    procedure IgnoreInvalidCert;
    constructor Create(const EndpointURL: String); virtual;
    /// <summary>
    /// Invokes [function Sum(const A: Integer; const B: Integer): Integer]
    /// Returns the sum of two integers
    /// </summary>
    function Sum(const A: Integer; const B: Integer): Integer;
    /// <summary>
    /// Invokes [function Diff(const A: Integer; const B: Integer): Integer]
    /// Returns the difference between two integers
    /// </summary>
    function Diff(const A: Integer; const B: Integer): Integer;
end;

implementation

constructor TCalculatorRPCProxy.Create(const EndpointURL: String);
begin
  inherited Create;
  fRPCExecutor := TMVCJSONRPCExecutor.Create(EndpointURL);
  fRPCExecutor.AddHTTPHeader(TNetHeader.Create('Accept-Encoding', 'gzip,deflate'));
  fRPCExecutor.AddHTTPHeader(TNetHeader.Create('User-Agent', 'dmscontainer-delphi-proxy'));

end;

function TCalculatorRPCProxy.NewReqID: Int64;
begin
  Result := 10000 + Random(10000000);
end;

function TCalculatorRPCProxy.RPCExecutor: IMVCJSONRPCExecutor;
begin
  Result := fRPCExecutor;
end;

procedure TCalculatorRPCProxy.IgnoreInvalidCert;
begin
  fRPCExecutor.SetOnValidateServerCertificate(IgnoreInvalidServerCertificate);
end;

procedure TCalculatorRPCProxy.IgnoreInvalidServerCertificate(
  const Sender: TObject; const ARequest: TURLRequest;
  const Certificate: TCertificate; var Accepted: Boolean);
begin
  Accepted := True;
end;


function TCalculatorRPCProxy.Sum(const A: Integer; const B: Integer): Integer;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'Sum');
  lReq.Params.Add(A);
  lReq.Params.Add(B);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.Result.AsInteger;
end;


function TCalculatorRPCProxy.Diff(const A: Integer; const B: Integer): Integer;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'Diff');
  lReq.Params.Add(A);
  lReq.Params.Add(B);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.Result.AsInteger;
end;

end.
