//------------------------------------------------------------------
// Proxy Unit Generated by Delphi Microservices Container 4.0.20
// Do not modify this unit!
// Generated at: 2021-03-05 12:46:41
//------------------------------------------------------------------
unit EmailRPCProxy;

interface

uses
  System.SysUtils,
  System.Classes,
  MVCFramework.JSONRPC,
  MVCFramework.JSONRPC.Client,
  MVCFramework.Serializer.Commons,
  JsonDataObjects;

type
  IEmailRPCProxy = interface
  ['{1BB6B7EB-D7D6-49D4-AC66-4D663CE49ACD}']
    function RPCExecutor: IMVCJSONRPCExecutor;
    /// <summary>
    /// Invokes [procedure SetUserSender(const Token: string; const UserID: Int64; aSender: TJsonObject)]
    /// </summary>
    procedure SetUserSender(const Token: string; const UserID: Int64; aSender: TJsonObject);
    /// <summary>
    /// Invokes [function RemoveUserSender(const Token: string; const UserID: Int64): TJsonObject]
    /// </summary>
    function RemoveUserSender(const Token: string; const UserID: Int64): TJDOJsonObject;
    /// <summary>
    /// Invokes [function GetUserSender(const Token: string; const UserID: Int64): TSender]
    /// </summary>
    function GetUserSender(const Token: string; const UserID: Int64): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessagesByUserName(const Token: string; const SenderUserName: string): TObjectList<Jobs.Email.Entities.TMessage>]
    /// Returns the messages sent by SenderUserName
    /// </summary>
    function GetMessagesByUserName(const Token: string; const SenderUserName: string): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMyMessages(const Token: string; const StatusList: TJsonArray): TObjectList<Jobs.Email.Entities.TMessage>]
    /// Returns the messages owned by the logged user
    /// </summary>
    function GetMyMessages(const Token: string; const StatusList: TJsonArray): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessageByID(const Token: string; const MessageID: Int64): TMessage]
    /// Returns the message with id MessageID
    /// </summary>
    function GetMessageByID(const Token: string; const MessageID: Int64): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessagesByStatus(const Token: string; const StatusList: TJsonArray): TObjectList<Jobs.Email.Entities.TMessage>]
    /// Returns the messages with the status contained in the StatusList array
    /// </summary>
    function GetMessagesByStatus(const Token: string; const StatusList: TJsonArray): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessagesByRQL(const Token: string; const Filter: TJsonObject): TJsonObject]
    /// Returns all messages (up to 6 months) which match the filter.rql property
    /// </summary>
    function GetMessagesByRQL(const Token: string; const Filter: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function SendMessage(const Token: string; const aMessage: TJsonObject): TJsonObject]
    /// Send a message using information stored in aMessage
    /// </summary>
    function SendMessage(const Token: string; const aMessage: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function DeleteMessageByID(const Token: string; const MessageID: Int64): TJsonObject]
    /// </summary>
    function DeleteMessageByID(const Token: string; const MessageID: Int64): TJDOJsonObject;
    /// <summary>
    /// Invokes [function AdminSendMessage(const Token: string; const SenderUserName: string; const aMessage: TJsonObject): TJsonObject]
    /// </summary>
    function AdminSendMessage(const Token: string; const SenderUserName: string; const aMessage: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function AdminSendTestMessage(const Token: string; const SenderUserName: string; const Recipient: string): TJsonObject]
    /// </summary>
    function AdminSendTestMessage(const Token: string; const SenderUserName: string; const Recipient: string): TJDOJsonObject;
    /// <summary>
    /// Invokes [function CreateMessage(const Token: string; const aMessage: TJsonObject): TJsonObject]
    /// </summary>
    function CreateMessage(const Token: string; const aMessage: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function AddAttachmentToMessage(const Token: string; const aMessageID: Int64; const aIsRelated: Boolean; const aAttachment: TJsonObject): TJsonObject]
    /// </summary>
    function AddAttachmentToMessage(const Token: string; const aMessageID: Int64; const aIsRelated: Boolean; const aAttachment: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function CompleteMessage(const Token: string; const aMessageID: Int64): TJsonObject]
    /// </summary>
    function CompleteMessage(const Token: string; const aMessageID: Int64): TJDOJsonObject;
    /// <summary>
    /// Invokes [function BulkSendMessages(const Token: string; const aMetaMessage: TJsonObject; const aBulkMessagesData: TJsonObject): TJsonObject]
    /// </summary>
    function BulkSendMessages(const Token: string; const aMetaMessage: TJsonObject; const aBulkMessagesData: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function Login(const UserName: string; const Password: string): TJsonObject]
    /// Returns the JWT token which can be used to call all other methods.
    /// </summary>
    function Login(const UserName: string; const Password: string): TJDOJsonObject;
    /// <summary>
    /// Invokes [function RefreshToken(const Token: string): TJsonObject]
    /// Extends the expiration time of a still-valid token. Clients must use the token returned instead of the previous one.
    /// </summary>
    function RefreshToken(const Token: string): TJDOJsonObject;
  end;

  TEmailRPCProxy = class(TInterfacedObject, IEmailRPCProxy)
  protected
    fRPCExecutor: IMVCJSONRPCExecutor;
    function NewReqID: Int64;
  public
    function RPCExecutor: IMVCJSONRPCExecutor;
    constructor Create(const EndpointURL: String); virtual;
    /// <summary>
    /// Invokes [procedure SetUserSender(const Token: string; const UserID: Int64; aSender: TJsonObject)]
    /// </summary>
    procedure SetUserSender(const Token: string; const UserID: Int64; aSender: TJsonObject);
    /// <summary>
    /// Invokes [function RemoveUserSender(const Token: string; const UserID: Int64): TJsonObject]
    /// </summary>
    function RemoveUserSender(const Token: string; const UserID: Int64): TJDOJsonObject;
    /// <summary>
    /// Invokes [function GetUserSender(const Token: string; const UserID: Int64): TSender]
    /// </summary>
    function GetUserSender(const Token: string; const UserID: Int64): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessagesByUserName(const Token: string; const SenderUserName: string): TObjectList<Jobs.Email.Entities.TMessage>]
    /// Returns the messages sent by SenderUserName
    /// </summary>
    function GetMessagesByUserName(const Token: string; const SenderUserName: string): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMyMessages(const Token: string; const StatusList: TJsonArray): TObjectList<Jobs.Email.Entities.TMessage>]
    /// Returns the messages owned by the logged user
    /// </summary>
    function GetMyMessages(const Token: string; const StatusList: TJsonArray): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessageByID(const Token: string; const MessageID: Int64): TMessage]
    /// Returns the message with id MessageID
    /// </summary>
    function GetMessageByID(const Token: string; const MessageID: Int64): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessagesByStatus(const Token: string; const StatusList: TJsonArray): TObjectList<Jobs.Email.Entities.TMessage>]
    /// Returns the messages with the status contained in the StatusList array
    /// </summary>
    function GetMessagesByStatus(const Token: string; const StatusList: TJsonArray): IJSONRPCResponse;
    /// <summary>
    /// Invokes [function GetMessagesByRQL(const Token: string; const Filter: TJsonObject): TJsonObject]
    /// Returns all messages (up to 6 months) which match the filter.rql property
    /// </summary>
    function GetMessagesByRQL(const Token: string; const Filter: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function SendMessage(const Token: string; const aMessage: TJsonObject): TJsonObject]
    /// Send a message using information stored in aMessage
    /// </summary>
    function SendMessage(const Token: string; const aMessage: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function DeleteMessageByID(const Token: string; const MessageID: Int64): TJsonObject]
    /// </summary>
    function DeleteMessageByID(const Token: string; const MessageID: Int64): TJDOJsonObject;
    /// <summary>
    /// Invokes [function AdminSendMessage(const Token: string; const SenderUserName: string; const aMessage: TJsonObject): TJsonObject]
    /// </summary>
    function AdminSendMessage(const Token: string; const SenderUserName: string; const aMessage: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function AdminSendTestMessage(const Token: string; const SenderUserName: string; const Recipient: string): TJsonObject]
    /// </summary>
    function AdminSendTestMessage(const Token: string; const SenderUserName: string; const Recipient: string): TJDOJsonObject;
    /// <summary>
    /// Invokes [function CreateMessage(const Token: string; const aMessage: TJsonObject): TJsonObject]
    /// </summary>
    function CreateMessage(const Token: string; const aMessage: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function AddAttachmentToMessage(const Token: string; const aMessageID: Int64; const aIsRelated: Boolean; const aAttachment: TJsonObject): TJsonObject]
    /// </summary>
    function AddAttachmentToMessage(const Token: string; const aMessageID: Int64; const aIsRelated: Boolean; const aAttachment: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function CompleteMessage(const Token: string; const aMessageID: Int64): TJsonObject]
    /// </summary>
    function CompleteMessage(const Token: string; const aMessageID: Int64): TJDOJsonObject;
    /// <summary>
    /// Invokes [function BulkSendMessages(const Token: string; const aMetaMessage: TJsonObject; const aBulkMessagesData: TJsonObject): TJsonObject]
    /// </summary>
    function BulkSendMessages(const Token: string; const aMetaMessage: TJsonObject; const aBulkMessagesData: TJsonObject): TJDOJsonObject;
    /// <summary>
    /// Invokes [function Login(const UserName: string; const Password: string): TJsonObject]
    /// Returns the JWT token which can be used to call all other methods.
    /// </summary>
    function Login(const UserName: string; const Password: string): TJDOJsonObject;
    /// <summary>
    /// Invokes [function RefreshToken(const Token: string): TJsonObject]
    /// Extends the expiration time of a still-valid token. Clients must use the token returned instead of the previous one.
    /// </summary>
    function RefreshToken(const Token: string): TJDOJsonObject;
end;

implementation

uses
  System.Net.URLClient,
  System.RTTI;

constructor TEmailRPCProxy.Create(const EndpointURL: String);
begin
  inherited Create;
  fRPCExecutor := TMVCJSONRPCExecutor.Create(EndpointURL);
  fRPCExecutor.AddHTTPHeader(TNetHeader.Create('Accept-Encoding', 'gzip'));
  fRPCExecutor.AddHTTPHeader(TNetHeader.Create('User-Agent', 'dmscontainer-delphi-proxy'));

end;

function TEmailRPCProxy.NewReqID: Int64;
begin
  Result := 10000 + Random(10000000);
end;

function TEmailRPCProxy.RPCExecutor: IMVCJSONRPCExecutor;
begin
  Result := fRPCExecutor;
end;


procedure TEmailRPCProxy.SetUserSender(const Token: string; const UserID: Int64; aSender: TJsonObject);
var
  lNotification: IJSONRPCNotification;
begin
  lNotification := TJSONRPCNotification.Create('SetUserSender');
  lNotification.Params.Add(Token);
  lNotification.Params.Add(UserID, TJSONRPCParamDataType.pdtLongInteger);
  lNotification.Params.Add(aSender);
  fRPCExecutor.ExecuteNotification(lNotification);
end;


function TEmailRPCProxy.RemoveUserSender(const Token: string; const UserID: Int64): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'RemoveUserSender');
  lReq.Params.Add(Token);
  lReq.Params.Add(UserID, TJSONRPCParamDataType.pdtLongInteger);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.GetUserSender(const Token: string; const UserID: Int64): IJSONRPCResponse;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'GetUserSender');
  lReq.Params.Add(Token);
  lReq.Params.Add(UserID, TJSONRPCParamDataType.pdtLongInteger);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp; //TSender
end;


function TEmailRPCProxy.GetMessagesByUserName(const Token: string; const SenderUserName: string): IJSONRPCResponse;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'GetMessagesByUserName');
  lReq.Params.Add(Token);
  lReq.Params.Add(SenderUserName);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp; //TObjectList<Jobs.Email.Entities.TMessage>
end;


function TEmailRPCProxy.GetMyMessages(const Token: string; const StatusList: TJsonArray): IJSONRPCResponse;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'GetMyMessages');
  lReq.Params.Add(Token);
  lReq.Params.Add(StatusList);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp; //TObjectList<Jobs.Email.Entities.TMessage>
end;


function TEmailRPCProxy.GetMessageByID(const Token: string; const MessageID: Int64): IJSONRPCResponse;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'GetMessageByID');
  lReq.Params.Add(Token);
  lReq.Params.Add(MessageID, TJSONRPCParamDataType.pdtLongInteger);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp; //TMessage
end;


function TEmailRPCProxy.GetMessagesByStatus(const Token: string; const StatusList: TJsonArray): IJSONRPCResponse;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'GetMessagesByStatus');
  lReq.Params.Add(Token);
  lReq.Params.Add(StatusList);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp; //TObjectList<Jobs.Email.Entities.TMessage>
end;


function TEmailRPCProxy.GetMessagesByRQL(const Token: string; const Filter: TJsonObject): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'GetMessagesByRQL');
  lReq.Params.Add(Token);
  lReq.Params.Add(Filter);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.SendMessage(const Token: string; const aMessage: TJsonObject): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'SendMessage');
  lReq.Params.Add(Token);
  lReq.Params.Add(aMessage);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.DeleteMessageByID(const Token: string; const MessageID: Int64): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'DeleteMessageByID');
  lReq.Params.Add(Token);
  lReq.Params.Add(MessageID, TJSONRPCParamDataType.pdtLongInteger);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.AdminSendMessage(const Token: string; const SenderUserName: string; const aMessage: TJsonObject): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'AdminSendMessage');
  lReq.Params.Add(Token);
  lReq.Params.Add(SenderUserName);
  lReq.Params.Add(aMessage);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.AdminSendTestMessage(const Token: string; const SenderUserName: string; const Recipient: string): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'AdminSendTestMessage');
  lReq.Params.Add(Token);
  lReq.Params.Add(SenderUserName);
  lReq.Params.Add(Recipient);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.CreateMessage(const Token: string; const aMessage: TJsonObject): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'CreateMessage');
  lReq.Params.Add(Token);
  lReq.Params.Add(aMessage);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.AddAttachmentToMessage(const Token: string; const aMessageID: Int64; const aIsRelated: Boolean; const aAttachment: TJsonObject): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'AddAttachmentToMessage');
  lReq.Params.Add(Token);
  lReq.Params.Add(aMessageID, TJSONRPCParamDataType.pdtLongInteger);
  lReq.Params.Add(aIsRelated);
  lReq.Params.Add(aAttachment);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.CompleteMessage(const Token: string; const aMessageID: Int64): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'CompleteMessage');
  lReq.Params.Add(Token);
  lReq.Params.Add(aMessageID, TJSONRPCParamDataType.pdtLongInteger);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.BulkSendMessages(const Token: string; const aMetaMessage: TJsonObject; const aBulkMessagesData: TJsonObject): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'BulkSendMessages');
  lReq.Params.Add(Token);
  lReq.Params.Add(aMetaMessage);
  lReq.Params.Add(aBulkMessagesData);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.Login(const UserName: string; const Password: string): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'Login');
  lReq.Params.Add(UserName);
  lReq.Params.Add(Password);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;


function TEmailRPCProxy.RefreshToken(const Token: string): TJDOJsonObject;
var
  lReq: IJSONRPCRequest;
  lResp: IJSONRPCResponse;
begin
  lReq := TJSONRPCRequest.Create(NewReqID, 'RefreshToken');
  lReq.Params.Add(Token);
  lResp := fRPCExecutor.ExecuteRequest(lReq);
  Result := lResp.ResultAsJSONObject.Clone as TJDOJsonObject; //TJsonObject
end;

end.
